package org.junit.tests.experimental;

import org.junit.experimental.categories.AllCategoriesTests;
import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;
import org.junit.tests.experimental.max.AllMaxTests;
import org.junit.tests.experimental.parallel.AllParallelTests;
import org.junit.tests.experimental.results.AllResultsTests;
import org.junit.tests.experimental.results.PrintableResultTest;
import org.junit.tests.experimental.results.ResultMatchersTest;
import org.junit.tests.experimental.theories.AllTheoriesTests;
import org.junit.tests.experimental.theories.ParameterSignatureTest;
import org.junit.tests.experimental.theories.extendingwithstubs.StubbedTheoriesTest;
import org.junit.tests.experimental.theories.internal.ParameterizedAssertionErrorTest;
import org.junit.tests.experimental.theories.internal.SpecificDataPointsSupplierTest;
import org.junit.tests.experimental.theories.runner.SuccessfulWithDataPointFields;
import org.junit.tests.experimental.theories.runner.UnsuccessfulWithDataPointFields;
import org.junit.tests.experimental.theories.runner.WhenNoParametersMatch;
import org.junit.tests.experimental.theories.runner.WithAutoGeneratedDataPoints;
import org.junit.tests.experimental.theories.runner.WithDataPointMethod;
import org.junit.tests.experimental.theories.runner.WithExtendedParameterSources;
import org.junit.tests.experimental.theories.runner.WithNamedDataPoints;
import org.junit.tests.experimental.theories.runner.WithOnlyTestAnnotations;
import org.junit.tests.experimental.theories.runner.WithUnresolvedGenericTypeVariablesOnTheoryParms;

@RunWith(Suite.class)
@SuiteClasses({
        AllCategoriesTests.class,
        AllMaxTests.class,
        AllParallelTests.class,
        AllResultsTests.class,
        AllTheoriesTests.class,
        AssumptionTest.class,
        MatcherTest.class,
        StubbedTheoriesTest.class
})
public class AllExperimentalTests {
}
